### ISSUE TITLE
emerge --depclean fails due to dev-java/icu4j:70 dependency

### ISSUE THREAD

**Issue by slackline** [msva/mva-overlay#182]
Hi,

I've found Portage complains about the 

```bash
 # emerge --depclean
 * Dependencies could not be completely resolved due to
 * the following required packages not being installed:
 * 
 *   dev-java/icu4j:70 pulled in by:
 *     app-text/ltex-ls-16.0.0
 * 
 * Have you forgotten to do a complete update prior to depclean? The
 * most comprehensive command for this purpose is as follows:
 * 
 *   emerge --update --newuse --deep --with-bdeps=y @world
 * 
 * Note that the --with-bdeps=y option is not required in many
 * situations. Refer to the emerge manual page (run `man emerge`)
 * for more information about --with-bdeps.
 * 
 * Also, note that it may be necessary to manually uninstall
 * packages that no longer exist in the repository, since it may not
 * be possible to satisfy their dependencies.
```

I've had a go at switch the slot to `dev-java/icu4j:0` and re-emerging and whilst it it builds ok on running it fails with...

```bash
❱ ltex-ls 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/bsplines/ltexls/LtexLanguageServerLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

...which is probably something on my side but I'm unsure what.

**Comment by msva** [comment]
Looks like maintainers in gentoo repo moved icu4j that has SLOT="70" to SLOT="0"

I'll try to fix that in near time

**Comment by slackline** [comment]
Thanks @msva and no rush.

I switched a copy of the ebuild for `ltex-ls` to `SLOT="0"` and `ltex-ls` build ok although it didn't seem to rebuild `icu4j`.
